- hosts: all
  gather_facts: yes
  tasks:
    - name: Save essential system facts
      copy:
        content: |
          {
            "hostname": "{{ ansible_hostname }}",
            "os_family": "{{ ansible_os_family }}",
            "distribution": "{{ ansible_distribution }}",
            "distribution_version": "{{ ansible_distribution_version }}",
            "architecture": "{{ ansible_architecture }}",
            "cpu_cores": "{{ ansible_processor_cores }}",
            "ram_total": "{{ ansible_memtotal_mb }} MB",
            "disk_space": "{{ ansible_devices.sda.size }}"
          }
        dest: "./facts_{{ inventory_hostname }}.json"
